import { sqliteTable, text, integer, real, blob } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull().default("member"),
  createdAt: integer("created_at").notNull(),
});

export const categories = sqliteTable("categories", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  isAutoGenerated: integer("is_auto_generated").notNull().default(1),
  createdAt: integer("created_at").notNull(),
});

export const pages = sqliteTable("pages", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  plainText: text("plain_text").notNull(),
  summary: text("summary"),
  categoryId: text("category_id").references(() => categories.id),
  authorId: text("author_id")
    .notNull()
    .references(() => users.id),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const pageVersions = sqliteTable("page_versions", {
  id: text("id").primaryKey(),
  pageId: text("page_id")
    .notNull()
    .references(() => pages.id),
  version: integer("version").notNull(),
  content: text("content").notNull(),
  plainText: text("plain_text").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const tags = sqliteTable("tags", {
  id: text("id").primaryKey(),
  name: text("name").notNull().unique(),
});

export const pageTags = sqliteTable("page_tags", {
  id: text("id").primaryKey(),
  pageId: text("page_id")
    .notNull()
    .references(() => pages.id),
  tagId: text("tag_id")
    .notNull()
    .references(() => tags.id),
  confidence: real("confidence").notNull(),
  source: text("source").notNull(),
});

export const embeddings = sqliteTable("embeddings", {
  id: text("id").primaryKey(),
  pageId: text("page_id")
    .notNull()
    .unique()
    .references(() => pages.id),
  vector: blob("vector").notNull(),
  clusterId: integer("cluster_id"),
});

export const reports = sqliteTable("reports", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  periodStart: integer("period_start").notNull(),
  periodEnd: integer("period_end").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const files = sqliteTable("files", {
  id: text("id").primaryKey(),
  filename: text("filename").notNull(),
  storagePath: text("storage_path").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  pageId: text("page_id").references(() => pages.id),
  uploadedBy: text("uploaded_by")
    .notNull()
    .references(() => users.id),
  createdAt: integer("created_at").notNull(),
});

// Relations

export const usersRelations = relations(users, ({ many }) => ({
  pages: many(pages),
  files: many(files),
}));

export const categoriesRelations = relations(categories, ({ many }) => ({
  pages: many(pages),
}));

export const pagesRelations = relations(pages, ({ one, many }) => ({
  author: one(users, { fields: [pages.authorId], references: [users.id] }),
  category: one(categories, {
    fields: [pages.categoryId],
    references: [categories.id],
  }),
  versions: many(pageVersions),
  pageTags: many(pageTags),
  embedding: one(embeddings, {
    fields: [pages.id],
    references: [embeddings.pageId],
  }),
  files: many(files),
}));

export const pageVersionsRelations = relations(pageVersions, ({ one }) => ({
  page: one(pages, {
    fields: [pageVersions.pageId],
    references: [pages.id],
  }),
}));

export const tagsRelations = relations(tags, ({ many }) => ({
  pageTags: many(pageTags),
}));

export const pageTagsRelations = relations(pageTags, ({ one }) => ({
  page: one(pages, { fields: [pageTags.pageId], references: [pages.id] }),
  tag: one(tags, { fields: [pageTags.tagId], references: [tags.id] }),
}));

export const embeddingsRelations = relations(embeddings, ({ one }) => ({
  page: one(pages, {
    fields: [embeddings.pageId],
    references: [pages.id],
  }),
}));

export const filesRelations = relations(files, ({ one }) => ({
  page: one(pages, { fields: [files.pageId], references: [pages.id] }),
  uploader: one(users, { fields: [files.uploadedBy], references: [users.id] }),
}));
