import { sqliteTable, text, integer, real, blob } from "drizzle-orm/sqlite-core";
import { relations } from "drizzle-orm";

export const users = sqliteTable("users", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash").notNull(),
  role: text("role").notNull().default("member"),
  createdAt: integer("created_at").notNull(),
});

export const categories = sqliteTable("categories", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  isAutoGenerated: integer("is_auto_generated").notNull().default(1),
  createdAt: integer("created_at").notNull(),
});

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  status: text("status").notNull().default("planned"),
  ownerId: text("owner_id")
    .notNull()
    .references(() => users.id),
  startDate: integer("start_date"),
  endDate: integer("end_date"),
  aiSummary: text("ai_summary"),
  progress: integer("progress").notNull().default(0),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const milestones = sqliteTable("milestones", {
  id: text("id").primaryKey(),
  projectId: text("project_id")
    .notNull()
    .references(() => projects.id),
  title: text("title").notNull(),
  description: text("description"),
  status: text("status").notNull().default("pending"),
  startDate: integer("start_date"),
  endDate: integer("end_date"),
  sortOrder: integer("sort_order").notNull().default(0),
  aiProgress: integer("ai_progress").notNull().default(0),
  aiSummary: text("ai_summary"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const pages = sqliteTable("pages", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  plainText: text("plain_text").notNull(),
  summary: text("summary"),
  categoryId: text("category_id").references(() => categories.id),
  authorId: text("author_id")
    .notNull()
    .references(() => users.id),
  projectId: text("project_id").references(() => projects.id),
  milestoneId: text("milestone_id").references(() => milestones.id),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const pageVersions = sqliteTable("page_versions", {
  id: text("id").primaryKey(),
  pageId: text("page_id")
    .notNull()
    .references(() => pages.id),
  version: integer("version").notNull(),
  content: text("content").notNull(),
  plainText: text("plain_text").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const tags = sqliteTable("tags", {
  id: text("id").primaryKey(),
  name: text("name").notNull().unique(),
});

export const pageTags = sqliteTable("page_tags", {
  id: text("id").primaryKey(),
  pageId: text("page_id")
    .notNull()
    .references(() => pages.id),
  tagId: text("tag_id")
    .notNull()
    .references(() => tags.id),
  confidence: real("confidence").notNull(),
  source: text("source").notNull(),
});

export const embeddings = sqliteTable("embeddings", {
  id: text("id").primaryKey(),
  pageId: text("page_id")
    .notNull()
    .unique()
    .references(() => pages.id),
  vector: blob("vector").notNull(),
  clusterId: integer("cluster_id"),
});

export const reports = sqliteTable("reports", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  title: text("title").notNull(),
  content: text("content").notNull(),
  periodStart: integer("period_start").notNull(),
  periodEnd: integer("period_end").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const files = sqliteTable("files", {
  id: text("id").primaryKey(),
  filename: text("filename").notNull(),
  storagePath: text("storage_path").notNull(),
  mimeType: text("mime_type").notNull(),
  size: integer("size").notNull(),
  pageId: text("page_id").references(() => pages.id),
  uploadedBy: text("uploaded_by")
    .notNull()
    .references(() => users.id),
  createdAt: integer("created_at").notNull(),
});

// Relations

export const usersRelations = relations(users, ({ many }) => ({
  pages: many(pages),
  files: many(files),
  projects: many(projects),
}));

export const categoriesRelations = relations(categories, ({ many }) => ({
  pages: many(pages),
}));

export const projectsRelations = relations(projects, ({ one, many }) => ({
  owner: one(users, { fields: [projects.ownerId], references: [users.id] }),
  milestones: many(milestones),
  pages: many(pages),
}));

export const milestonesRelations = relations(milestones, ({ one, many }) => ({
  project: one(projects, {
    fields: [milestones.projectId],
    references: [projects.id],
  }),
  pages: many(pages),
}));

export const pagesRelations = relations(pages, ({ one, many }) => ({
  author: one(users, { fields: [pages.authorId], references: [users.id] }),
  category: one(categories, {
    fields: [pages.categoryId],
    references: [categories.id],
  }),
  project: one(projects, {
    fields: [pages.projectId],
    references: [projects.id],
  }),
  milestone: one(milestones, {
    fields: [pages.milestoneId],
    references: [milestones.id],
  }),
  versions: many(pageVersions),
  pageTags: many(pageTags),
  embedding: one(embeddings, {
    fields: [pages.id],
    references: [embeddings.pageId],
  }),
  files: many(files),
  databases: many(databases),
}));

export const pageVersionsRelations = relations(pageVersions, ({ one }) => ({
  page: one(pages, {
    fields: [pageVersions.pageId],
    references: [pages.id],
  }),
}));

export const tagsRelations = relations(tags, ({ many }) => ({
  pageTags: many(pageTags),
}));

export const pageTagsRelations = relations(pageTags, ({ one }) => ({
  page: one(pages, { fields: [pageTags.pageId], references: [pages.id] }),
  tag: one(tags, { fields: [pageTags.tagId], references: [tags.id] }),
}));

export const embeddingsRelations = relations(embeddings, ({ one }) => ({
  page: one(pages, {
    fields: [embeddings.pageId],
    references: [pages.id],
  }),
}));

export const filesRelations = relations(files, ({ one }) => ({
  page: one(pages, { fields: [files.pageId], references: [pages.id] }),
  uploader: one(users, { fields: [files.uploadedBy], references: [users.id] }),
}));

// === Database (inline database) tables ===

export const databases = sqliteTable("databases", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  pageId: text("page_id")
    .notNull()
    .references(() => pages.id),
  createdBy: text("created_by")
    .notNull()
    .references(() => users.id),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const databaseProperties = sqliteTable("database_properties", {
  id: text("id").primaryKey(),
  databaseId: text("database_id")
    .notNull()
    .references(() => databases.id),
  name: text("name").notNull(),
  type: text("type").notNull(), // text|number|select|multi_select|date|checkbox|url|email|phone|person|relation|formula
  config: text("config"), // JSON
  sortOrder: integer("sort_order").notNull().default(0),
  isTitle: integer("is_title").notNull().default(0),
  createdAt: integer("created_at").notNull(),
});

export const databaseRecords = sqliteTable("database_records", {
  id: text("id").primaryKey(),
  databaseId: text("database_id")
    .notNull()
    .references(() => databases.id),
  values: text("values").notNull().default("{}"), // JSON: { propertyId: value }
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const databaseViews = sqliteTable("database_views", {
  id: text("id").primaryKey(),
  databaseId: text("database_id")
    .notNull()
    .references(() => databases.id),
  name: text("name").notNull(),
  type: text("type").notNull(), // table|board|timeline|calendar|list|gallery|chart|feed|map
  config: text("config"), // JSON
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// Database relations

export const databasesRelations = relations(databases, ({ one, many }) => ({
  page: one(pages, { fields: [databases.pageId], references: [pages.id] }),
  creator: one(users, { fields: [databases.createdBy], references: [users.id] }),
  properties: many(databaseProperties),
  records: many(databaseRecords),
  views: many(databaseViews),
}));

export const databasePropertiesRelations = relations(databaseProperties, ({ one }) => ({
  database: one(databases, {
    fields: [databaseProperties.databaseId],
    references: [databases.id],
  }),
}));

export const databaseRecordsRelations = relations(databaseRecords, ({ one }) => ({
  database: one(databases, {
    fields: [databaseRecords.databaseId],
    references: [databases.id],
  }),
}));

export const databaseViewsRelations = relations(databaseViews, ({ one }) => ({
  database: one(databases, {
    fields: [databaseViews.databaseId],
    references: [databases.id],
  }),
}));
